export interface ApiClub {
  id: number;
  campus_id?: string | null;
  campus_name?: string;
  name: string;
  slug: string;
  objective?: string;
  about?: string;
  open_to_all?: boolean;
  instagram?: string;
  linkedin?: string;
  member_count?: number;
  president_name?: string;
  president_email?: string;
  president_photo?: string | null;
  vice_president_name?: string;
  vice_president_email?: string;
  vice_president_photo?: string | null;
  chapter_description?: string;
  contact_email?: string;
  chapter_is_active?: boolean;
  logo_url?: string;
  cover_image?: string;
  article_count?: number;
  is_active: boolean;
  campus_ids?: string[];
  campus_names?: string[];
  campus_chapters?: Array<{
    campus_id: string;
    campus_name: string;
    member_count: number;
    open_to_all: boolean;
    president_name: string;
    president_email: string;
    president_photo?: string | null;
    vice_president_name: string;
    vice_president_email: string;
    vice_president_photo?: string | null;
    instagram?: string;
    linkedin?: string;
    chapter_description: string;
    contact_email: string;
    is_active: boolean;
    updated_at: string;
  }>;
  created_at?: string;
  updated_at: string;
}
